### ISSUE TITLE
Service offline?

### ISSUE THREAD

**Issue by sirbrillig** [tombh/dharma-api#7]
Any request to the service's URL (including requesting a key) results in:

<img width="358" alt="screen shot 2016-02-25 at 12 07 42 pm" src="https://cloud.githubusercontent.com/assets/2036909/13327564/66bf3380-dbb8-11e5-8db5-b726496d26b5.png">

It looks like this project might be abandoned, but if not, it would be great to be able to access this API!

**Comment by tombh** [comment]
Ah damn, let me see if I can figure that out ....

**Comment by tombh** [comment]
I'm still working on this.

What had happened was that the MongoDB instance got upgraded to a version that is no longer supported by the MongoMapper gem that I use here. So I'm currently in the middle of complete rewrite using the Mongoid gem instead.

Crazy looking at this code again after so many years. It was my first every ruby project!

**Comment by tombh** [comment]
Back online!

**Comment by sundeepgupta** [comment]
I guess the service is offline again?

**Comment by samridh90** [comment]
@sundeepgupta : Did you try dharma-api.com or dharma-api.herokuapp.com? The former doesn't work for me whereas the latter does
